#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

cd "$1" || exit
find . -type f -name "__init__.py" | sed 's#/[^/]*$##' | cut -c 3- | sed 's|/|.|g'
